# mkdocs.yml
site_name: UVMultiFit
site_url: https://github.com/onsala-space-observatory/UVMultiFit

theme:
   name: "readthedocs"

plugins:
   - mkdocstrings

nav:
   - Home: index.md
   - Installation: install.md
   - Manual: manual.md
