from typing import List, Any

def is_valid_python(param: str) -> bool:  ...
def is_casa_position(param: str) -> bool: ...
def is_valid_stokes(param: str) -> bool: ...
def is_list_of_floats(param: Any, length=2) -> bool: ...
def is_list_of_int(param: Any) -> bool: ...
def get_list_of_strings(param: Any) -> List[str]: ...
def check_proper_motion(pm: Any, model: List[str]) -> List[List[float]]: ...
